#!/bin/zsh
DIALOG_CANCEL=1
DIALOG_ESC=255

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  cluster=$(dialog \
  --backtitle "Hyundai Motor Company - Connected Car Service" \
  --title "Choose cluster (Apply)" \
  --clear \
  --cancel-label "Exit" \
  --menu "Select Server :" 0 0 5 \
  "ap-northeast-1-stg" "KR 1센터 검증계" \
  "ap-northeast-2-dev" "KR 2센터 개발계" \
  "ap-northeast-2-stg" "KR 2센터 검증계" \
  "ap-northeast-2-prd" "KR 2센터 운영계" \
  2>&1 1>&3)

  exit_status=$?
  exec 3>&-

  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Manufactured by Hyundai Motor Company"
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac

  clear
  terraform workspace select $cluster
  terraform apply -var-file=./$cluster.tfvars -auto-approve
  exit
done

echo $selection


